<table class="popover" style="width: 100%;">
	<thead>
		<tr style="text-align:center;"><th colspan="2" class="ou-help">Popover</th></tr>
		<tr>
			<th class="ou-help">Link Text</th>
			<th class="ou-help">Popover Header Text</th>
			<th class="ou-help">Popover Body Text</th>
			<th class="ou-help">Placement<br/><small>You can choose either: left, right, top, or bottom.</small></th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td class="popover-link">Click Here for Popover Text Box</td>
			<td class="popover-header">Popover Header Text</td>
			<td class="popover-content">
				Lorem ipsum dolor sit amet, consectetur adipiscing elit. 
				Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. 
				Sed nisi. Nulla quis sem at nibh elementum imperdiet. 
				Duis sagittis ipsum. Praesent mauris. Fusce nec tellus sed augue semper porta. 
				Mauris massa. Vestibulum lacinia arcu eget nulla.
			</td>
			<td class="popover-placement">right</td>
		</tr>
	</tbody>
</table>
<h3 class="wysiwyg-spacer">PRESS ENTER HERE FOR A NEW LINE-&gt;</h3>
